"""update user model

Revision ID: bb44e753e356
Revises: 071822673478
Create Date: 2025-06-22 16:13:12.497495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb44e753e356'
down_revision = '071822673478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))
        batch_op.drop_column('password_hush')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hush', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
